In [57]:
import tensorflow as tf
from sklearn import datasets
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import os

In [58]:
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

In [59]:
t = np.arange(9).reshape((3,3))
tensor = tf.convert_to_tensor(t, dtype = float)
tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [60]:
tf.zeros((3,3))#ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [61]:
tf.random.uniform((4,4), minval = 0, maxval = 10, dtype = tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 8, 3, 7],
       [9, 5, 2, 7],
       [4, 9, 2, 7],
       [7, 1, 0, 7]])>

In [62]:
tf.random.normal((3, 3), mean=0, stddev=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.956899 , -3.7983375,  4.655621 ],
       [-0.5047833,  1.4956621, -5.6437845],
       [-0.7017001,  2.9308996,  0.781127 ]], dtype=float32)>

In [63]:
data = datasets.load_iris()
X = data.data
y = data.target
X_1 = data.data[:4]
X_2 = data.data[4:8]
tensor_1 = tf.convert_to_tensor(X_1)
tensor_2 = tf.convert_to_tensor(X_2)

#print(tf.add(tensor_1, tensor_2))
#tf.matmul(tensor_1, tensor_2)
X.shape

(150, 4)

In [64]:
tf.linalg.det(tf.matmul(tensor_1, tensor_2))

<tf.Tensor: shape=(), dtype=float64, numpy=3.844000000007259e-05>

In [65]:
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(4),
    tf.keras.layers.Dense(4)
])

In [66]:
model.compile(optimizer = 'adam', loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)) #metrics = ['accracy'])

In [67]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size= 0.2)
X_train = tf.convert_to_tensor(X_train)
y_train = tf.convert_to_tensor(y_train)

In [68]:
nn = model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 2.6772
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.7115  
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5635 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.4212 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.3755 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.1390 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 1.9714 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0935  
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.6963 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.8243  
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.6753 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5307 
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5877 
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.5092 
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4563 
Epoch 16/100
4/4

In [69]:
#test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)

In [ ]:
#test_model = tf.keras.Sequential([
#    model,
#    tf.keras.layers.Softmax()
#])
#predictions = probability_model.predict(samples_features)
#np.argmax(prediction[i])

#predictions = model.predict(y_test)

In [ ]:
inputX = np.array([[1.,3.],[1.,2.],[1.,1.5],
[1.5,2.],[2.,3.],[2.5,1.5],
[2.,1.],[3.,1.],[3.,2.],
[3.5,1.],[3.5,3.]])
inputY = [[1.,0.]]*6+ [[0.,1.]]*5
yc = [0]*5 + [1]*6

train_features = tf.convert_to_tensor(inputX)
train_labels = tf.convert_to_tensor(inputY)

plt.scatter(inputX[:,0],inputX[:,1],c=yc, s=50, alpha=0.9)
plt.show()

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2),
    tf.keras.layers.Dense(2)
])

model.compile(
    optimizer='SGD',
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=['accuracy']
)

history = model.fit(train_features, train_labels, epochs = 100)

In [ ]:
acc_set = history.history['loss']
epoch_set = history.epoch

plt.title("Ratio")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.scatter(epoch_set, acc_set, s = 10, alpha = 0.8, label='Training phase')

In [ ]:
testX = np.array([[1.,2.25],[1.25,3.],
[2,2.5],[2.25,2.75],
[2.5,3.],[2.,0.9],
[2.5,1.2],[3.,1.25],
[3.,1.5],[3.5,2.],
[3.5,2.5]])
testY = [[1.,0.]]*5 + [[0.,1.]]*6
test_features = tf.convert_to_tensor(testX)
test_labels = tf.convert_to_tensor(testY)

test_loss, test_acc = model.evaluate(test_features, test_labels, verbose=2)

In [ ]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
exp_features = 3*np.random.random((1000,2))
predictions = probability_model.predict(exp_features)
predictions

In [ ]:
np.argmax(predictions[1])

In [ ]:
yc = predictions[:,1]
plt.scatter(exp_features[:,0],exp_features[:,1],c=yc, s=50, alpha=1)
plt.show()

In [ ]:
yc = np.round(predictions[:,1])
plt.scatter(exp_features[:,0],exp_features[:,1],c=yc, s=50, alpha=1)
plt.show()